name: Update Copyright Year

on:
  schedule:
    - cron: '0 0 1 1 *' # Runs yearly on January 1st
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  update-year:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update copyright year
      run: |
        current_year=$(date +"%Y")
        sed -i "s/copyright: \".*\"/copyright: \"$current_year. CC BY-NC-SA 4.0\"/" py-pkgs/_config.yml

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add py-pkgs/_config.yml
        git commit -m "Update copyright year to $current_year"
        git push